import firebase from "firebase/compat/app";
import "firebase/compat/firestore";

// Helper to create timestamp from date string (YYYY-MM-DD)
const createTimestamp = (dateStr: string) => {
    return firebase.firestore.Timestamp.fromDate(new Date(dateStr));
};

export const ACADEMIC_EVENTS = [
    {
        id: "academic-1",
        title: "Commencement of Instruction",
        description: "Start of Semester II for F.Y. B.Tech.",
        date: createTimestamp("2026-02-02T09:00:00"),
        venue: "PICT Campus",
        organizer: "Academic Section",
        attendees: [],
    },
    {
        id: "academic-2",
        title: "Rangvarsha 2026",
        description: "Faculty Annual Gathering",
        date: createTimestamp("2026-02-14T10:00:00"),
        venue: "PICT Campus",
        organizer: "PICT",
        attendees: [],
    },
    {
        id: "academic-3",
        title: "Chhatrapati Shivaji Maharaj Jayanti",
        description: "Holiday",
        date: createTimestamp("2026-02-19T00:00:00"),
        venue: "N/A",
        organizer: "Holiday",
        attendees: [],
    },
    {
        id: "academic-4",
        title: "TechFiesta 2026",
        description: "PICT International Hackathon",
        date: createTimestamp("2026-02-21T09:00:00"),
        venue: "PICT Campus",
        organizer: "PICT ACM/CSI",
        attendees: [],
    },
    {
        id: "academic-5",
        title: "PICTO FEST",
        description: "Annual Technical Festival",
        date: createTimestamp("2026-02-23T09:00:00"),
        venue: "PICT Campus",
        organizer: "Student Council",
        attendees: [],
    },
    {
        id: "academic-6",
        title: "ADDICTION-2026",
        description: "Annual Social Gathering",
        date: createTimestamp("2026-02-26T17:00:00"),
        venue: "PICT Campus",
        organizer: "Student Council",
        attendees: [],
    },
    {
        id: "academic-7",
        title: "Holi Second Day",
        description: "Holiday",
        date: createTimestamp("2026-03-03T00:00:00"),
        venue: "N/A",
        organizer: "Holiday",
        attendees: [],
    },
    {
        id: "academic-8",
        title: "In-semester Examination (ISE)",
        description: " exams for F.Y. B.Tech.",
        date: createTimestamp("2026-03-04T09:00:00"),
        venue: "Exam Section",
        organizer: "Exam Section",
        attendees: [],
    },
    {
        id: "academic-9",
        title: "Gudi Padwa",
        description: "Holiday",
        date: createTimestamp("2026-03-19T00:00:00"),
        venue: "N/A",
        organizer: "Holiday",
        attendees: [],
    },
    {
        id: "academic-10",
        title: "Impetus and Concepts (INC)-2026",
        description: "Flagship Technical Event",
        date: createTimestamp("2026-03-20T09:00:00"),
        venue: "PICT Campus",
        organizer: "PICT",
        attendees: [],
    },
    {
        id: "academic-11",
        title: "Mahavir Janmakalyanak",
        description: "Holiday",
        date: createTimestamp("2026-03-31T00:00:00"),
        venue: "N/A",
        organizer: "Holiday",
        attendees: [],
    },
    {
        id: "academic-12",
        title: "Good Friday",
        description: "Holiday",
        date: createTimestamp("2026-04-03T00:00:00"),
        venue: "N/A",
        organizer: "Holiday",
        attendees: [],
    },
    {
        id: "academic-13",
        title: "Dr. Babasaheb Ambedkar Jayanti",
        description: "Holiday",
        date: createTimestamp("2026-04-14T00:00:00"),
        venue: "N/A",
        organizer: "Holiday",
        attendees: [],
    },
    {
        id: "academic-14",
        title: "Maharashtra Din",
        description: "Holiday",
        date: createTimestamp("2026-05-01T00:00:00"),
        venue: "N/A",
        organizer: "Holiday",
        attendees: [],
    },
    {
        id: "academic-15",
        title: "End Semester Examination (ESE)",
        description: "Final Exams",
        date: createTimestamp("2026-05-25T09:00:00"),
        venue: "Exam Section",
        organizer: "Exam Section",
        attendees: [],
    },
];
